'use strict';

exports.Genders = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
};

exports.ClanRanks = {
  MEMBER: 'MEMBER',
  COLEADER: 'COLEADER',
  LEADER: 'LEADER',
};

exports.ItemTypes = {
  GOLD: 'GOLD',
  ROSE_PACKAGE: 'ROSE',
  GEM: 'GEM',
  XP: 'XP',
  ROLE_CARD: 'ROLE_CARD',
  AVATAR_ITEM: 'AVATAR_ITEM',
  LOOT_BOX: 'LOOT_BOX',
  PROFILE_ICON: 'PROFILE_ICON',
  EMOJI: 'EMOJI',
  BACKGROUND: 'BACKGROUND',
  LOADING_SCREEN: 'LOADING_SCREEN',
  ROLE_CARD_ABILITY_EXCHANGE_VOUCHER: 'ROLE_CARD_ABILITY_EXCHANGE_VOUCHER',
  TALISMAN: 'TALISMAN',
  ITEM_SET: 'ITEM_SET',
  ROLE_ICON: 'ROLE_ICON',
  ITEM_COLLECTION: 'ITEM_COLLECTION',
};

exports.Status = {
  DEFAULT: 'DEFAULT',
  PLAY: 'PLAY',
  DND: 'DND',
  OFFLINE: 'OFFLINE',
};

exports.AvatarItemTypes = {
  HAT: 'HAT',
  HAIR: 'HAIR',
  EYES: 'EYES',
  GLASSES: 'GLASSES',
  MOUTH: 'MOUTH',
  MASK: 'MASK',
  CLOTHES: 'CLOTHES',
  FOREGROUND: 'FOREGROUND',
  BACKGROUND: 'BACKGROUND',
  BADGE: 'BADGE',
  GRAVESTONE: 'GRAVESTONE',
};

exports.Rarities = {
  COMMON: 'COMMON',
  RARE: 'RARE',
  EPIC: 'EPIC',
  LEGENDARY: 'LEGENDARY',
};

exports.ClanLedgerActions = {
  CREATE_CLAN: 'CREATE_CLAN',
  DONATE: 'DONATE',
  CLAN_ICON: 'CLAN_ICON',
  CLAN_QUEST: 'CLAN_QUEST',
  CLAN_QUEST_SHUFFLE: 'CLAN_QUEST_SHUFFLE',
  CLAN_QUEST_SKIP_WAIT: 'CLAN_QUEST_SKIP_WAIT',
  CLAN_QUEST_CLAIM_TIME: 'CLAN_QUEST_CLAIM_TIME',
};

exports.ClanActions = {
  BLACKLIST_ADDED: 'BLACKLIST_ADDED',
  BLACKLIST_REMOVED: 'BLACKLIST_REMOVED',
  JOIN_REQUEST_SENT_BY_CLAN: 'JOIN_REQUEST_SENT_BY_CLAN',
  JOIN_REQUEST_SENT_BY_EXTERNAL_PLAYER: 'JOIN_REQUEST_SENT_BY_EXTERNAL_PLAYER',
  JOIN_REQUEST_ACCEPTED: 'JOIN_REQUEST_ACCEPTED',
  JOIN_REQUEST_DECLINED_BY_CLAN: 'JOIN_REQUEST_DECLINED_BY_CLAN',
  JOIN_REQUEST_DECLINED_BY_EXTERNAL_PLAYER: 'JOIN_REQUEST_DECLINED_BY_EXTERNAL_PLAYER',
  JOIN_REQUEST_WITHDRAWN: 'JOIN_REQUEST_WITHDRAWN',
  LEADER_CHANGED: 'LEADER_CHANGED',
  CO_LEADER_PROMOTED: 'CO_LEADER_PROMOTED',
  CO_LEADER_DEMOTED: 'CO_LEADER_DEMOTED',
  CO_LEADER_RESIGNED: 'CO_LEADER_RESIGNED',
  PLAYER_LEFT: 'PLAYER_LEFT',
  PLAYER_KICKED: 'PLAYER_KICKED',
  PLAYER_JOINED: 'PLAYER_JOINED',
  PLAYER_QUEST_PARTICIPATION_ENABLED: 'PLAYER_QUEST_PARTICIPATION_ENABLED',
  PLAYER_QUEST_PARTICIPATION_DISABLED: 'PLAYER_QUEST_PARTICIPATION_DISABLED',
};
