name: Publish dev
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

permissions:
  contents: read

concurrency:
  group: publish-dev
  cancel-in-progress: false

jobs:
  npm:
    name: npm
    runs-on: ubuntu-latest
    if: github.repository_owner == 'wolvesvillejs'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Check previous released version
        id: pre-release
        run: |
          if [[ $(npm view wolvesville.js@dev version | grep -e "$(jq --raw-output '.version' package.json)\..*-$(git rev-parse --short HEAD)") ]]; \
          then echo "release=false" >> $GITHUB_OUTPUT; \
          else echo "release=true" >> $GITHUB_OUTPUT; fi

      - name: Install dependencies
        if: steps.pre-release.outputs.release == 'true'
        run: npm ci

      - name: Publish
        if: steps.pre-release.outputs.release == 'true'
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          npm version $(jq --raw-output '.version' package.json).$(date +%s)-$(git rev-parse --short HEAD)
          npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.WJS_PUBLISH }}
